kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  networking:
    annotations:
      kubernetes.io/ingress.class:  "nginx"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.org/websocket-services: "che-gateway"
    auth:
      externalIdentityProvider: true
      oAuthClientName: "$KEYCLOAK_CHE_CLIENT_ID"
      oAuthSecret: "$KEYCLOAK_CHE_CLIENT_SECRET"
      identityProviderURL: "$KEYCLOAK_EXTERNAL_URL/realms/master"
      openShiftoAuth: false
      gateway:
        deployment:
          containers:
            - name: oauth-proxy
              env:
              - name: OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL
                value: "true"
              - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
                value: "true"
              - name: OAUTH2_PROXY_OIDC_EMAIL_CLAIM
                value: email
              - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
                value: "true"
              - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
                value: "true"
  components:
    cheServer:
      extraProperties:
        CHE_OIDC_EMAIL__CLAIM: email
        CHE_OIDC_USERNAME__CLAIM: email
